// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbukxlafawxusvjcyucp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidWt4bGFmYXd4dXN2amN5dWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTg0OTcsImV4cCI6MjA3Mzc3NDQ5N30.F3PUR480VzRIR6ia-sUotyX8gdm6oIFVl0F_VEh2uSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});